# Generated by Django 4.0.1 on 2022-02-02 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='post/%Y/%m')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 19, 28, 10, 269233))),
            ],
        ),
    ]
