# Generated by Django 4.0.1 on 2022-02-12 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 11, 22, 44, 721459, tzinfo=utc)),
        ),
    ]
