# Generated by Django 4.0.1 on 2022-02-12 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_date_alter_message_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nevim',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 13, 15, 19, 112654, tzinfo=utc)),
        ),
    ]
