# Generated by Django 4.0.1 on 2022-02-12 14:44

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_message_nevim_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 14, 44, 2, 861661, tzinfo=utc)),
        ),
    ]
