# Generated by Django 4.0.1 on 2022-02-12 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_slug_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 14, 45, 42, 720032, tzinfo=utc)),
        ),
    ]
